package kr.co.bookand.backend.common;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
@AllArgsConstructor
public enum ErrorCode {
    NOT_FOUND("COMMON-ERR-404","PAGE NOT FOUND", 404),
    INPUT_VALID_ERROR("COMMON-ERR-400","INPUT VALID ERROR", 400),
    INTER_SERVER_ERROR("COMMON-ERR-500","INTER SERVER ERROR", 400),
    EMAIL_DUPLICATION("MEMBER-ERR-300","EMAIL DUPLICATED", 400),
    NICKNAME_DUPLICATION("MEMBER-ERR-301","NICKNAME DUPLICATED", 400),
    JWT_ERROR("JWT-ERR-100","JWT EXCEPTION", 401),

    NOT_ROLE_MEMBER("MEMBER-ERR-302","NOT AUTHENTICATION ROLE", 403),
    NOT_FOUND_MEMBER("MEMBER-ERR-100","NOT FOUND MEMBER", 404),
    NOT_FOUND_POLICY("POLICY-ERR-100", "NOT FOUND POLICY", 404),
    NOT_FOUND_BOOKSTORE("BOOKSTORE-ERR-100", "NOT FOUND BOOKSTORE", 404),
    NOT_FOUND_ARTICLE("ARTICLE-ERR-100", "NOT FOUND ARTICLE", 404),

    HTTP_CLIENT_ERROR("HTTP-ERR-100", "HTTP CLIENT ERROR", 400),
    APPLE_LOGIN_ERROR("MEMBER-ERR-201", "APPLE_LOGIN_ERROR", 400),
    GOOGLE_LOGIN_ERROR("MEMBER-ERROR-200", "GOOGLE_LOGIN_ERROR", 404)
    ;

    private String errorCode;
    private String message;
    private int httpStatus;
}