# This is a basic workflow to help you get started with Actions
name: bookand ci/cd

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

env:
  PROJECT_NAME: bookand_project
  BUCKET_NAME: bookand-codedeploy
  CODE_DEPLOY_APP_NAME: bookand
  DEPLOYMENT_GROUP_NAME: bookand-cicd-codedeploy


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
          
      - name: Setup Java JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      
      - name: Copy Secret
        env: 
          OCCUPY_SECRET: ${{ secrets.OCCUPY_SECRET }}
          OCCUPY_SECRET_DIR: src/main/resources
          OCCUPY_SECRET_DIR_FILE_NAME: application-secret.properties
        run: echo $OCCUPY_SECRET | base64 --decode > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_DIR_FILE_NAME
          
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash
      
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash